version: "3"
services:
    react-app:
        container_name: "react-app"
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "4000:3000"
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
    test-runner:
        container_name: "test-runner"
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/usr/app
            - /usr/app/node_modules
        command: ["npm", "run", "test"]
