FROM node:alpine AS build-stage
WORKDIR /usr/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx as run-stage
EXPOSE 80
COPY --from=build-stage /usr/app/build /usr/share/nginx/html
